export const FLUID_PROPS_PARAMETERS = [
  {
    propsParameter: "DELTA",
    idName: "Delta",
    units: "",
    input: true,
    trivial: false,
    description: "Reduced density (rho/rhoc)",
  },
  {
    propsParameter: "DMOLAR",
    idName: "DMolar",
    units: "mol/m^3",
    input: true,
    trivial: false,
    description: "Molar density",
  },
  {
    propsParameter: "D",
    idName: "DMass",
    units: "kg/m^3",
    input: true,
    trivial: false,
    description: "Mass density",
  },
  {
    propsParameter: "HMOLAR",
    idName: "HMolar",
    units: "J/mol",
    input: true,
    trivial: false,
    description: "Molar specific enthalpy",
  },
  {
    propsParameter: "H",
    idName: "HMass",
    units: "J/kg",
    input: true,
    trivial: false,
    description: "Mass specific enthalpy",
  },
  {
    propsParameter: "P",
    idName: "P",
    units: "Pa",
    input: true,
    trivial: false,
    description: "Pressure",
  },
  {
    propsParameter: "Q",
    idName: "Q",
    units: "mol/mol",
    input: true,
    trivial: false,
    description: "Molar vapor quality",
  },
  {
    propsParameter: "SMOLAR",
    idName: "SMolar",
    units: "J/mol/K",
    input: true,
    trivial: false,
    description: "Molar specific entropy",
  },
  {
    propsParameter: "S",
    idName: "SMass",
    units: "J/kg/K",
    input: true,
    trivial: false,
    description: "Mass specific entropy",
  },
  {
    propsParameter: "TAU",
    idName: "Tau",
    units: "",
    input: true,
    trivial: false,
    description: "Reciprocal reduced temperature (Tc/T)",
  },
  {
    propsParameter: "T",
    idName: "T",
    units: "K",
    input: true,
    trivial: false,
    description: "Temperature",
  },
  {
    propsParameter: "UMOLAR",
    idName: "UMolar",
    units: "J/mol",
    input: true,
    trivial: false,
    description: "Molar specific internal energy",
  },
  {
    propsParameter: "U",
    idName: "UMass",
    units: "J/kg",
    input: true,
    trivial: false,
    description: "Mass specific internal energy",
  },
  {
    propsParameter: "ACENTRIC",
    idName: "Acentric",
    units: "",
    input: false,
    trivial: true,
    description: "Acentric factor",
  },
  {
    propsParameter: "ALPHA0",
    idName: "Alpha0",
    units: "",
    input: false,
    trivial: false,
    description: "Ideal Helmholtz energy",
  },
  {
    propsParameter: "ALPHAR",
    idName: "AlphaR",
    units: "",
    input: false,
    trivial: false,
    description: "Residual Helmholtz energy",
  },
  {
    propsParameter: "A",
    idName: "SoundSpeed",
    units: "m/s",
    input: false,
    trivial: false,
    description: "Speed of sound",
  },
  {
    propsParameter: "BVIRIAL",
    idName: "BVirial",
    units: "",
    input: false,
    trivial: false,
    description: "Second virial coefficient",
  },
  {
    propsParameter: "CONDUCTIVITY",
    idName: "Conductivity",
    units: "W/m/K",
    input: false,
    trivial: false,
    description: "Thermal conductivity",
  },
  {
    propsParameter: "CP0MASS",
    idName: "Cp0Mass",
    units: "J/kg/K",
    input: false,
    trivial: false,
    description: "Ideal gas mass specific constant pressure specific heat",
  },
  {
    propsParameter: "CP0MOLAR",
    idName: "Cp0Molar",
    units: "J/mol/K",
    input: false,
    trivial: false,
    description: "Ideal gas molar specific constant pressure specific heat",
  },
  {
    propsParameter: "CPMOLAR",
    idName: "CpMolar",
    units: "J/mol/K",
    input: false,
    trivial: false,
    description: "Molar specific constant pressure specific heat",
  },
  {
    propsParameter: "CVIRIAL",
    idName: "CVirial",
    units: "",
    input: false,
    trivial: false,
    description: "Third virial coefficient",
  },
  {
    propsParameter: "CVMASS",
    idName: "CvMass",
    units: "J/kg/K",
    input: false,
    trivial: false,
    description: "Mass specific constant volume specific heat",
  },
  {
    propsParameter: "CVMOLAR",
    idName: "CvMolar",
    units: "J/mol/K",
    input: false,
    trivial: false,
    description: "Molar specific constant volume specific heat",
  },
  {
    propsParameter: "C",
    idName: "CpMass",
    units: "J/kg/K",
    input: false,
    trivial: false,
    description: "Mass specific constant pressure specific heat",
  },
  {
    propsParameter: "D2ALPHA0_DDELTA2_CONSTTAU",
    idName: "D2Alpha0DDelta2",
    units: "",
    input: false,
    trivial: false,
    description: "Second derivative of ideal Helmholtz energy with delta",
  },
  {
    propsParameter: "D3ALPHA0_DDELTA3_CONSTTAU",
    idName: "D3Alpha0DDelta3",
    units: "",
    input: false,
    trivial: false,
    description: "Third derivative of ideal Helmholtz energy with delta",
  },
  {
    propsParameter: "DALPHA0_DDELTA_CONSTTAU",
    idName: "DAlpha0DDelta",
    units: "",
    input: false,
    trivial: false,
    description: "Derivative of ideal Helmholtz energy with delta",
  },
  {
    propsParameter: "DALPHA0_DTAU_CONSTDELTA",
    idName: "DAlpha0DTau",
    units: "",
    input: false,
    trivial: false,
    description: "Derivative of ideal Helmholtz energy with tau",
  },
  {
    propsParameter: "DALPHAR_DDELTA_CONSTTAU",
    idName: "DAlphaRDDelta",
    units: "",
    input: false,
    trivial: false,
    description: "Derivative of residual Helmholtz energy with delta",
  },
  {
    propsParameter: "DALPHAR_DTAU_CONSTDELTA",
    idName: "DAlphaRDTau",
    units: "",
    input: false,
    trivial: false,
    description: "Derivative of residual Helmholtz energy with tau",
  },
  {
    propsParameter: "DBVIRIAL_DT",
    idName: "DBVirialDT",
    units: "",
    input: false,
    trivial: false,
    description: "Derivative of second virial coefficient with respect to T",
  },
  {
    propsParameter: "DCVIRIAL_DT",
    idName: "DCVirialDT",
    units: "",
    input: false,
    trivial: false,
    description: "Derivative of third virial coefficient with respect to T",
  },
  {
    propsParameter: "DIPOLE_MOMENT",
    idName: "DipoleMoment",
    units: "C m",
    input: false,
    trivial: true,
    description: "Dipole moment",
  },
  {
    propsParameter: "FH",
    idName: "FH",
    units: "",
    input: false,
    trivial: true,
    description: "Flammability hazard",
  },
  {
    propsParameter: "FRACTION_MAX",
    idName: "FractionMax",
    units: "",
    input: false,
    trivial: true,
    description: "Fraction (mole, mass, volume) maximum value for incompressible solutions",
  },
  {
    propsParameter: "FRACTION_MIN",
    idName: "FractionMin",
    units: "",
    input: false,
    trivial: true,
    description: "Fraction (mole, mass, volume) minimum value for incompressible solutions",
  },
  {
    propsParameter: "FUNDAMENTAL_DERIVATIVE_OF_GAS_DYNAMICS",
    idName: "FundDerivGasDyn",
    units: "",
    input: false,
    trivial: false,
    description: "Fundamental derivative of gas dynamics",
  },
  {
    propsParameter: "GAS_CONSTANT",
    idName: "GasConstant",
    units: "J/mol/K",
    input: false,
    trivial: true,
    description: "Molar gas constant",
  },
  {
    propsParameter: "GMOLAR_RESIDUAL",
    idName: "GMolarResidual",
    units: "J/mol/K",
    input: false,
    trivial: false,
    description: "Residual molar Gibbs energy",
  },
  {
    propsParameter: "GMOLAR",
    idName: "GMolar",
    units: "J/mol",
    input: false,
    trivial: false,
    description: "Molar specific Gibbs energy",
  },
  {
    propsParameter: "GWP100",
    idName: "GWP100",
    units: "",
    input: false,
    trivial: true,
    description: "100-year global warming potential",
  },
  {
    propsParameter: "GWP20",
    idName: "GWP20",
    units: "",
    input: false,
    trivial: true,
    description: "20-year global warming potential",
  },
  {
    propsParameter: "GWP500",
    idName: "GWP500",
    units: "",
    input: false,
    trivial: true,
    description: "500-year global warming potential",
  },
  {
    propsParameter: "G",
    idName: "GMass",
    units: "J/kg",
    input: false,
    trivial: false,
    description: "Mass specific Gibbs energy",
  },
  {
    propsParameter: "HELMHOLTZMASS",
    idName: "HelmholtzMass",
    units: "J/kg",
    input: false,
    trivial: false,
    description: "Mass specific Helmholtz energy",
  },
  {
    propsParameter: "HELMHOLTZMOLAR",
    idName: "HelmholtzMolar",
    units: "J/mol",
    input: false,
    trivial: false,
    description: "Molar specific Helmholtz energy",
  },
  {
    propsParameter: "HH",
    idName: "HH",
    units: "",
    input: false,
    trivial: true,
    description: "Health hazard",
  },
  {
    propsParameter: "HMOLAR_RESIDUAL",
    idName: "HMolarResidual",
    units: "J/mol/K",
    input: false,
    trivial: false,
    description: "Residual molar enthalpy",
  },
  {
    propsParameter: "ISENTROPIC_EXPANSION_COEFFICIENT",
    idName: "IsentropicExpansionCoefficient",
    units: "",
    input: false,
    trivial: false,
    description: "Isentropic expansion coefficient",
  },
  {
    propsParameter: "ISOBARIC_EXPANSION_COEFFICIENT",
    idName: "IsobaricExpansionCoefficient",
    units: "1/K",
    input: false,
    trivial: false,
    description: "Isobaric expansion coefficient",
  },
  {
    propsParameter: "ISOTHERMAL_COMPRESSIBILITY",
    idName: "IsothermalCompressibility",
    units: "1/Pa",
    input: false,
    trivial: false,
    description: "Isothermal compressibility",
  },
  {
    propsParameter: "I",
    idName: "SurfaceTension",
    units: "N/m",
    input: false,
    trivial: false,
    description: "Surface tension",
  },
  {
    propsParameter: "M",
    idName: "MolarMass",
    units: "kg/mol",
    input: false,
    trivial: true,
    description: "Molar mass",
  },
  {
    propsParameter: "ODP",
    idName: "ODP",
    units: "",
    input: false,
    trivial: true,
    description: "Ozone depletion potential",
  },
  {
    propsParameter: "PCRIT",
    idName: "PCrit",
    units: "Pa",
    input: false,
    trivial: true,
    description: "Pressure at the critical point",
  },
  {
    propsParameter: "PHASE",
    idName: "Phase",
    units: "",
    input: false,
    trivial: false,
    description: "Phase index as a float",
  },
  {
    propsParameter: "PH",
    idName: "PH",
    units: "",
    input: false,
    trivial: true,
    description: "Physical hazard",
  },
  {
    propsParameter: "PIP",
    idName: "PIP",
    units: "",
    input: false,
    trivial: false,
    description: "Phase identification parameter",
  },
  {
    propsParameter: "PMAX",
    idName: "PMax",
    units: "Pa",
    input: false,
    trivial: true,
    description: "Maximum pressure limit",
  },
  {
    propsParameter: "PMIN",
    idName: "PMin",
    units: "Pa",
    input: false,
    trivial: true,
    description: "Minimum pressure limit",
  },
  {
    propsParameter: "PRANDTL",
    idName: "Prandtl",
    units: "",
    input: false,
    trivial: false,
    description: "Prandtl number",
  },
  {
    propsParameter: "PTRIPLE",
    idName: "PTriplePoint",
    units: "Pa",
    input: false,
    trivial: true,
    description: "Pressure at the triple point (pure only)",
  },
  {
    propsParameter: "P_REDUCING",
    idName: "PReducing",
    units: "Pa",
    input: false,
    trivial: true,
    description: "Pressure at the reducing point",
  },
  {
    propsParameter: "RHOCRIT",
    idName: "RhoCrit",
    units: "kg/m^3",
    input: false,
    trivial: true,
    description: "Mass density at critical point",
  },
  {
    propsParameter: "RHOMASS_REDUCING",
    idName: "RhoMassReducing",
    units: "kg/m^3",
    input: false,
    trivial: true,
    description: "Mass density at reducing point",
  },
  {
    propsParameter: "RHOMOLAR_CRITICAL",
    idName: "RhoMolarCritical",
    units: "mol/m^3",
    input: false,
    trivial: true,
    description: "Molar density at critical point",
  },
  {
    propsParameter: "RHOMOLAR_REDUCING",
    idName: "RhoMolarReducing",
    units: "mol/m^3",
    input: false,
    trivial: true,
    description: "Molar density at reducing point",
  },
  {
    propsParameter: "SMOLAR_RESIDUAL",
    idName: "SMolarResidual",
    units: "J/mol/K",
    input: false,
    trivial: false,
    description: "Residual molar entropy (sr/R = s(T,rho) - s^0(T,rho))",
  },
  {
    propsParameter: "TCRIT",
    idName: "TCritical",
    units: "K",
    input: false,
    trivial: true,
    description: "Temperature at the critical point",
  },
  {
    propsParameter: "TMAX",
    idName: "TMax",
    units: "K",
    input: false,
    trivial: true,
    description: "Maximum temperature limit",
  },
  {
    propsParameter: "TMIN",
    idName: "TMin",
    units: "K",
    input: false,
    trivial: true,
    description: "Minimum temperature limit",
  },
  {
    propsParameter: "TTRIPLE",
    idName: "TTriplePoint",
    units: "K",
    input: false,
    trivial: true,
    description: "Temperature at the triple point",
  },
  {
    propsParameter: "T_FREEZE",
    idName: "TFreeze",
    units: "K",
    input: false,
    trivial: true,
    description: "Freezing temperature for incompressible solutions",
  },
  {
    propsParameter: "T_REDUCING",
    idName: "TReducing",
    units: "K",
    input: false,
    trivial: true,
    description: "Temperature at the reducing point",
  },
  {
    propsParameter: "V",
    idName: "Viscosity",
    units: "Pa s",
    input: false,
    trivial: false,
    description: "Viscosity",
  },
  {
    propsParameter: "Z",
    idName: "Z",
    units: "",
    input: false,
    trivial: false,
    description: "Compressibility factor",
  },
];


export const FLUIDS = [
  {
    propsName: "1-Butene",
    idName: "But1ene",
  },
  {
    propsName: "Acetone",
    idName: "Acetone",
  },
  {
    propsName: "Air",
    idName: "Air",
  },
  {
    propsName: "Ammonia",
    idName: "Ammonia",
  },
  {
    propsName: "Argon",
    idName: "Argon",
  },
  {
    propsName: "Benzene",
    idName: "Benzene",
  },
  {
    propsName: "CarbonDioxide",
    idName: "CarbonDioxide",
  },
  {
    propsName: "CarbonMonoxide",
    idName: "CarbonMonoxide",
  },
  {
    propsName: "CarbonylSulfide",
    idName: "CarbonylSulfide",
  },
  {
    propsName: "CycloHexane",
    idName: "CycloHexane",
  },
  {
    propsName: "CycloPropane",
    idName: "CycloPropane",
  },
  {
    propsName: "Cyclopentane",
    idName: "Cyclopentane",
  },
  {
    propsName: "D4",
    idName: "D4",
  },
  {
    propsName: "D5",
    idName: "D5",
  },
  {
    propsName: "D6",
    idName: "D6",
  },
  {
    propsName: "Deuterium",
    idName: "Deuterium",
  },
  {
    propsName: "Dichloroethane",
    idName: "Dichloroethane",
  },
  {
    propsName: "DiethylEther",
    idName: "DiethylEther",
  },
  {
    propsName: "DimethylCarbonate",
    idName: "DimethylCarbonate",
  },
  {
    propsName: "DimethylEther",
    idName: "DimethylEther",
  },
  {
    propsName: "Ethane",
    idName: "Ethane",
  },
  {
    propsName: "Ethanol",
    idName: "Ethanol",
  },
  {
    propsName: "EthylBenzene",
    idName: "EthylBenzene",
  },
  {
    propsName: "Ethylene",
    idName: "Ethylene",
  },
  {
    propsName: "EthyleneOxide",
    idName: "EthyleneOxide",
  },
  {
    propsName: "Fluorine",
    idName: "Fluorine",
  },
  {
    propsName: "HFE143m",
    idName: "HFE143m",
  },
  {
    propsName: "HeavyWater",
    idName: "HeavyWater",
  },
  {
    propsName: "Helium",
    idName: "Helium",
  },
  {
    propsName: "Hydrogen",
    idName: "Hydrogen",
  },
  {
    propsName: "HydrogenChloride",
    idName: "HydrogenChloride",
  },
  {
    propsName: "HydrogenSulfide",
    idName: "HydrogenSulfide",
  },
  {
    propsName: "IsoButane",
    idName: "IsoButane",
  },
  {
    propsName: "IsoButene",
    idName: "IsoButene",
  },
  {
    propsName: "Isohexane",
    idName: "Isohexane",
  },
  {
    propsName: "Isopentane",
    idName: "Isopentane",
  },
  {
    propsName: "Krypton",
    idName: "Krypton",
  },
  {
    propsName: "MD2M",
    idName: "MD2M",
  },
  {
    propsName: "MD3M",
    idName: "MD3M",
  },
  {
    propsName: "MD4M",
    idName: "MD4M",
  },
  {
    propsName: "MDM",
    idName: "MDM",
  },
  {
    propsName: "MM",
    idName: "MM",
  },
  {
    propsName: "Methane",
    idName: "Methane",
  },
  {
    propsName: "Methanol",
    idName: "Methanol",
  },
  {
    propsName: "MethylLinoleate",
    idName: "MethylLinoleate",
  },
  {
    propsName: "MethylLinolenate",
    idName: "MethylLinolenate",
  },
  {
    propsName: "MethylOleate",
    idName: "MethylOleate",
  },
  {
    propsName: "MethylPalmitate",
    idName: "MethylPalmitate",
  },
  {
    propsName: "MethylStearate",
    idName: "MethylStearate",
  },
  {
    propsName: "Neon",
    idName: "Neon",
  },
  {
    propsName: "Neopentane",
    idName: "Neopentane",
  },
  {
    propsName: "Nitrogen",
    idName: "Nitrogen",
  },
  {
    propsName: "NitrousOxide",
    idName: "NitrousOxide",
  },
  {
    propsName: "Novec649",
    idName: "Novec649",
  },
  {
    propsName: "OrthoDeuterium",
    idName: "OrthoDeuterium",
  },
  {
    propsName: "OrthoHydrogen",
    idName: "OrthoHydrogen",
  },
  {
    propsName: "Oxygen",
    idName: "Oxygen",
  },
  {
    propsName: "ParaDeuterium",
    idName: "ParaDeuterium",
  },
  {
    propsName: "ParaHydrogen",
    idName: "ParaHydrogen",
  },
  {
    propsName: "Propylene",
    idName: "Propylene",
  },
  {
    propsName: "Propyne",
    idName: "Propyne",
  },
  {
    propsName: "R11",
    idName: "R11",
  },
  {
    propsName: "R113",
    idName: "R113",
  },
  {
    propsName: "R114",
    idName: "R114",
  },
  {
    propsName: "R115",
    idName: "R115",
  },
  {
    propsName: "R116",
    idName: "R116",
  },
  {
    propsName: "R12",
    idName: "R12",
  },
  {
    propsName: "R123",
    idName: "R123",
  },
  {
    propsName: "R1233zd(E)",
    idName: "R1233zdE",
  },
  {
    propsName: "R1234yf",
    idName: "R1234yf",
  },
  {
    propsName: "R1234ze(E)",
    idName: "R1234zeE",
  },
  {
    propsName: "R1234ze(Z)",
    idName: "R1234zeZ",
  },
  {
    propsName: "R124",
    idName: "R124",
  },
  {
    propsName: "R1243zf",
    idName: "R1243zf",
  },
  {
    propsName: "R125",
    idName: "R125",
  },
  {
    propsName: "R13",
    idName: "R13",
  },
  {
    propsName: "R134a",
    idName: "R134a",
  },
  {
    propsName: "R13I1",
    idName: "R13I1",
  },
  {
    propsName: "R14",
    idName: "R14",
  },
  {
    propsName: "R141b",
    idName: "R141b",
  },
  {
    propsName: "R142b",
    idName: "R142b",
  },
  {
    propsName: "R143a",
    idName: "R143a",
  },
  {
    propsName: "R152A",
    idName: "R152A",
  },
  {
    propsName: "R161",
    idName: "R161",
  },
  {
    propsName: "R21",
    idName: "R21",
  },
  {
    propsName: "R218",
    idName: "R218",
  },
  {
    propsName: "R22",
    idName: "R22",
  },
  {
    propsName: "R227EA",
    idName: "R227EA",
  },
  {
    propsName: "R23",
    idName: "R23",
  },
  {
    propsName: "R236EA",
    idName: "R236EA",
  },
  {
    propsName: "R236FA",
    idName: "R236FA",
  },
  {
    propsName: "R245ca",
    idName: "R245ca",
  },
  {
    propsName: "R245fa",
    idName: "R245fa",
  },
  {
    propsName: "R32",
    idName: "R32",
  },
  {
    propsName: "R365MFC",
    idName: "R365MFC",
  },
  {
    propsName: "R40",
    idName: "R40",
  },
  {
    propsName: "R404A",
    idName: "R404A",
  },
  {
    propsName: "R407C",
    idName: "R407C",
  },
  {
    propsName: "R41",
    idName: "R41",
  },
  {
    propsName: "R410A",
    idName: "R410A",
  },
  {
    propsName: "R507A",
    idName: "R507A",
  },
  {
    propsName: "RC318",
    idName: "RC318",
  },
  {
    propsName: "SES36",
    idName: "SES36",
  },
  {
    propsName: "SulfurDioxide",
    idName: "SulfurDioxide",
  },
  {
    propsName: "SulfurHexafluoride",
    idName: "SulfurHexafluoride",
  },
  {
    propsName: "Toluene",
    idName: "Toluene",
  },
  {
    propsName: "Water",
    idName: "Water",
  },
  {
    propsName: "Xenon",
    idName: "Xenon",
  },
  {
    propsName: "cis-2-Butene",
    idName: "cis2Butene",
  },
  {
    propsName: "m-Xylene",
    idName: "mXylene",
  },
  {
    propsName: "n-Butane",
    idName: "nButane",
  },
  {
    propsName: "n-Decane",
    idName: "nDecane",
  },
  {
    propsName: "n-Dodecane",
    idName: "nDodecane",
  },
  {
    propsName: "n-Heptane",
    idName: "nHeptane",
  },
  {
    propsName: "n-Hexane",
    idName: "nHexane",
  },
  {
    propsName: "n-Nonane",
    idName: "nNonane",
  },
  {
    propsName: "n-Octane",
    idName: "nOctane",
  },
  {
    propsName: "n-Pentane",
    idName: "nPentane",
  },
  {
    propsName: "n-Propane",
    idName: "nPropane",
  },
  {
    propsName: "n-Undecane",
    idName: "nUndecane",
  },
  {
    propsName: "o-Xylene",
    idName: "oXylene",
  },
  {
    propsName: "p-Xylene",
    idName: "pXylene",
  },
  {
    propsName: "trans-2-Butene",
    idName: "trans2Butene",
  },
];
