<script lang="ts">
  import { onMount } from 'svelte';
  import { unit } from 'mathjs';
  import { results, cells, mathCellChanged } from './stores';
  import type { CodeFunctionQueryStatement } from './parser/types';
  import type { Cell } from './cells/Cells';
  import MathCell from './cells/MathCell';
  import { type FiniteImagResult, type Result, type MatrixResult, isMatrixResult } from './resultTypes';
  import { InlineLoading, CodeSnippet } from 'carbon-components-svelte';

  export let pyodidePromise: Promise<any>;
  export let index: number;

  let cell: Cell | undefined;
  let result: Result | FiniteImagResult | MatrixResult | null = null;
  let statement: CodeFunctionQueryStatement | null = null;
  let generatedCode = "";

  onMount(() => {
    if (statement) {
      statement.generateCode = true;

      $cells = $cells;
      $mathCellChanged = true;
    }
  });
  
  function getUnitsDescription(unitsString: string): string {
    if (unitsString === "") {
      return "is unitless.";
    } else {
      return `has units of [${unit(unitsString).formatUnits()}].`;
    }
  }

  function parameterMap(name: string, index: number) {
    return `    ${name} : float\n        '${name}' ${getUnitsDescription(statement.parameterUnits[index])}`;
  }

  $: cell = $cells[index]

  $: if (cell instanceof MathCell && cell.mathField.statement &&
        cell.mathField.statement.type === "query" && 
        cell.mathField.statement.isCodeFunctionQuery) {
      statement = cell.mathField.statement;
    } else {
      statement = null;
    }


  $: {
      const tempResult = $results[index];    
      if (tempResult && !(tempResult instanceof Array)) {
      result = tempResult;
    } else {
      result = null;
    }
  }

  $: if (statement && result && !isMatrixResult(result) && "generatedCode" in result && result.generatedCode) {
    generatedCode = `def ${statement.functionName}(${statement.parameterNames.join(", ")}):
    """
    Function '${statement.functionName}' automatically generated by EngineeringPaper.xyz

    Parameters
    ----------
${statement.parameterNames.map(parameterMap).join("\n")}

    Returns
    -------
    float
        Return value ${getUnitsDescription(result.units)}
    """

    result = ${result.generatedCode}
    
    return result
    `
  } else {
    generatedCode = "";
  }
</script>


{#await pyodidePromise}
  <InlineLoading description="Generating Python Code..."/>
{:then promiseReturn}
  {#if generatedCode}
    <CodeSnippet type="multi" code={generatedCode} expanded />
  {/if}
{:catch promiseError}
  <InlineLoading status="error" description={promiseError}/>
{/await}